id: AC39C61A9
title: 'The Chariot Bound for Sukhāvatī, the Blissful Realm: The Liturgy for Cultivating
  Buddha Amitābha’s Pure Realm'
type: translation
pechas:
- IACB83BAB
- I0B6B3088
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:16.316666
  last_modified_at: 2023-01-04 12:37:16.316672
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IACB83BAB/BB85: F075
  I0B6B3088/8242: F075
